language: java
install: true

jdk:
  - openjdk8

services:
  - postgresql

before_script:
  - chmod +x gradlew
  - psql -U postgres -f src/main/sql/schema.sql
  - mkdir config && cp .travis.database.yml config/database.yml

script:
  - ./gradlew build --scan -s

