language: java
install: true

jdk:
  - openjdk8

services:
  - postgresql

before_script:
  - chmod +x gradlew
  - psql -c 'create database library;' -U postgres
  - psql -U postgres -f src/main/sql/schema.sql -d library
  - mkdir config && cp .travis.database.yml config/database.yml

script:
  - ./gradlew build --scan -s
