language: java
install: true

jdk:
  - openjdk8

services:
  - postgresql

before_script:
  - chmod +x gradlew
  before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - cp ./database.yml.travis

script:
  - ./gradlew build --scan -s

